### ISSUE TITLE
Importing UNComponents to updated Xcode version fails due to compiling mismatch 

### ISSUE THREAD

**Issue by rakefetWorkiz** [unit-finance/unit-ios-components-pod#1]
Xcode version 15.0 
Run with MacBook Pro, Apple M1 Max, Mac OS: 14.0 (Sonoma)
And with MacBook Pro, Intel Chip, Mac OS: 14.2.1 (Sonoma)

When adding import for UNComponents the complier would complain saying: 

`Failed to build module 'UNComponents'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)', while this compiler is 'Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)'). Please select a toolchain which matches the SDK.`

According to this thread: https://developer.apple.com/forums/thread/674582 that kind of error happens when the library isn't built with Library Evolution enabled and contained in an XCFramework 

Please let me know if you need more data to understand the issue

**Comment by alonshp** [comment]
Hi @rakefetWorkiz,
Our team is aware of this issue. We have tags that are built on specific Xcode versions.
We will provide a release tag for you to use in your project.
